// packages/qwik-table/src/index.tsx
import * as Qwik from '@builder.io/qwik'

export * from '@tanstack/table-core'

import { type Table, createTable } from '@tanstack/table-core'
import type {
  RowData,
  TableOptions,
  TableOptionsResolved,
} from '@tanstack/table-core'

type QwikComps = Qwik.Component | Qwik.FunctionComponent

const isFunction = (comp: unknown): comp is Function =>
  typeof comp === 'function'

const isQwikComponent = (comp: unknown): comp is QwikComps =>
  isFunction(comp) && comp.name === 'QwikComponent'

export function flexRender<TProps extends object>(
  Comp: any, // TODO: add renderable type
  props: TProps,
) {
  return !Comp ? null : isQwikComponent(Comp) ? (
    <Comp {...props} />
  ) : isFunction(Comp) ? (
    Comp(props)
  ) : (
    Comp
  )
}

export function useQwikTable<TData extends RowData>(
  options: TableOptions<TData>,
) {
  // Compose in the generic options to the user options
  const resolvedOptions: TableOptionsResolved<TData> = {
    state: {},
    onStateChange: () => {},
    renderFallbackValue: null,
    ...options,
  }

  // Create a new table instance and store it in a Qwik store
  const table = Qwik.useStore<{
    instance: Qwik.NoSerialize<Table<TData>>
  }>({
    instance: Qwik.noSerialize(createTable(resolvedOptions)),
  })

  // By default, manage table state here using the table's initial state
  const state = Qwik.useSignal(table.instance!.initialState)

  // Compose the default state above with any user state. This will allow the user
  // to only control a subset of the state if desired.
  table.instance!.setOptions((prev) => ({
    ...prev,
    ...options,
    state: {
      ...state.value,
      ...options.state,
    },
    // Similarly, we'll maintain both our internal state and any user-provided
    // state.
    onStateChange: (updater) => {
      state.value = updater instanceof Function ? updater(state.value) : updater
      options.onStateChange?.(updater)
    },
  }))

  return table.instance!
}

// packages/solid-table/src/index.tsx
// /** @jsxImportSource solid-js */
import { createTable } from '@tanstack/table-core'
import { createComponent, createComputed, mergeProps } from 'solid-js'
import { createStore } from 'solid-js/store'
import type {
  RowData,
  TableOptions,
  TableOptionsResolved,
} from '@tanstack/table-core'

export * from '@tanstack/table-core'

export function flexRender<TProps extends {}>(Comp: any, props: TProps) {
  if (!Comp) return null

  if (typeof Comp === 'function') {
    return createComponent(Comp, props)
  }

  return Comp
}

export function createSolidTable<TData extends RowData>(
  options: TableOptions<TData>,
) {
  const resolvedOptions: TableOptionsResolved<TData> = mergeProps(
    {
      state: {}, // Dummy state
      onStateChange: () => {}, // noop
      renderFallbackValue: null,
      mergeOptions: (
        defaultOptions: TableOptions<TData>,
        options: Partial<TableOptions<TData>>,
      ) => {
        return mergeProps(defaultOptions, options) as TableOptions<TData>
      },
    },
    options,
  )

  const table = createTable<TData>(resolvedOptions)
  const [state, setState] = createStore(table.initialState)

  createComputed(() => {
    table.setOptions((prev) => {
      return mergeProps(prev, options, {
        state: mergeProps(state, options.state || {}),
        // Similarly, we'll maintain both our internal state and any user-provided
        // state.
        onStateChange: (updater: any) => {
          // merging isn't required because stores shallow update
          setState(updater)

          options.onStateChange?.(updater)
        },
      })
    })
  })

  return table
}
